application: bongpresent
version: 1
runtime: go
api_version: go1

handlers:
- url: /login
  script: _go_app

- url: /apply
  script: _go_app


- url: /chat
  script: _go_app


- url: /sign
  script: _go_app

- url: /index
  script: _go_app


- url: /.*
  script: _go_app

- url: /
  script: _go_app