application: moonschatt
version: 1
runtime: go
api_version: go1

handlers:
- url: /loginscreen.htm
  script: _go_app

- url: /applyscreen.htm
  script: _go_app


- url: /chat.htm
  script: _go_app


- url: /index.htm
  script: _go_app


- url: /.*
  script: _go_app

- url: /
  script: _go_app